### ISSUE TITLE
callable function to core

### ISSUE THREAD

**Issue by catalyst-support** [enigmampc/surface#1]
https://github.com/enigmampc/surface/blob/591da9c9696806a206344b12aed8566d7acf921e/src/surface/communication/core/ipc.py#L42

This should be the function signature and not the hash of the function:
https://github.com/enigmampc/surface/blob/develop/src/tests/test_worker.py#L36

**Comment by elichai** [comment]
This issue was moved to enigmampc/surface-internal#1
